import {
  Activity,
  AlertCircle,
  ArrowLeft,
  ArrowRight,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  Clock,
  Copy,
  CreditCard,
  DollarSign,
  Download,
  Edit,
  Eye,
  EyeOff,
  FileText,
  Filter,
  Folder,
  Grid,
  HelpCircle,
  Image,
  Info,
  LayoutDashboard,
  Link,
  List,
  Loader2,
  Lock,
  LogIn,
  LogOut,
  Mail,
  Menu,
  Minus,
  MoreHorizontal,
  MoreVertical,
  Package,
  Plus,
  PlusCircle,
  Search,
  Settings,
  ShoppingCart,
  SlidersHorizontal,
  Star,
  Tag,
  Trash2,
  User,
  Users,
  X,
  XCircle,
  type Icon as LucideIcon,
} from 'lucide-react';

export type Icon = LucideIcon;

export const Icons = {
  activity: Activity,
  alert: AlertCircle,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  calendar: Calendar,
  check: Check,
  checkCircle: CheckCircle,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  circle: Circle,
  clock: Clock,
  copy: Copy,
  creditCard: CreditCard,
  dollar: DollarSign,
  download: Download,
  edit: Edit,
  eye: Eye,
  eyeOff: EyeOff,
  file: FileText,
  filter: Filter,
  folder: Folder,
  grid: Grid,
  help: HelpCircle,
  image: Image,
  info: Info,
  layoutDashboard: LayoutDashboard,
  link: Link,
  list: List,
  loader: Loader2,
  lock: Lock,
  logIn: LogIn,
  logOut: LogOut,
  mail: Mail,
  menu: Menu,
  minus: Minus,
  moreHorizontal: MoreHorizontal,
  moreVertical: MoreVertical,
  package: Package,
  plus: Plus,
  plusCircle: PlusCircle,
  search: Search,
  settings: Settings,
  shoppingCart: ShoppingCart,
  sliders: SlidersHorizontal,
  star: Star,
  tag: Tag,
  trash: Trash2,
  user: User,
  users: Users,
  x: X,
  xCircle: XCircle,
};
